project:
  type: website
  output-dir: docs

website:
  title: "귬's"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/han-gyumin
      
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



