{
  "hash": "7d018c0f378bbb602242d565ec9ad05f",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Post With Code\"\nauthor: \"Harlow Malloc\"\ndate: \"2025-03-06\"\ncategories: [news, code, analysis]\nimage: \"image.jpg\"\n---\n\n# palmer_penguins 요약\n\n## 1. 데이터 로드 및 기본 정보 확인\n\n::: {#d53d9ede .cell execution_count=1}\n``` {.python .cell-code}\n# 라이브러리 로드\nfrom palmerpenguins import load_penguins\nimport pandas as pd\n\n# 데이터 불러오기\npenguins = load_penguins()\n\n# 데이터 확인\npenguins.head() # 상위 5개 행 출력\npenguins[\"species\"].unique()  # 종 확인\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\narray(['Adelie', 'Gentoo', 'Chinstrap'], dtype=object)\n```\n:::\n:::\n\n\n<div>\n\n|    Column Name    |         의미          |          예제 값           |\n|:-----------------:|:---------------------:|:--------------------------:|\n|      species      |       펭귄의 종       | Adelie, Chinstreap, Gentoo |\n|      island       | 펭귄이 발견된 섬 이름 |  Torgersen, Biscoe, Dream  |\n|  bill_length_mm   |    부리 길이 (mm)     |      39.1, 48.7, 50.0      |\n|   bill_depth_mm   |    부리 깊이 (mm)     |      18.7, 17.4, 15.9      |\n| flipper_length_mm |    날개 길이 (mm)     |       181, 195, 210        |\n|    body_mass_g    |       체중 (g)        |      3750, 3800, 5000      |\n|        sex        |         성별          |        male, female        |\n|       year        |   데이터 수집 연도    |      2007, 2008, 2009      |\n\n</div>\n\n## 2. 종별 주요 특징 (평균값 비교)\n\n``` python\n# 종별 요약 통계 계산\nspecies_summary = penguins.groupby(\"species\").describe()\n\n# 종별 주요 특징 출력\nprint(species_summary['bill_length_mm'])  # 부리 길이\nprint(species_summary['bill_depth_mm'])  # 부리 깊이\nprint(species_summary['flipper_length_mm'])  # 날개 길이\nprint(species_summary['body_mass_g'])  # 몸무게\n```\n\n|    종     | 부리 길이 | 부리 깊이 | 날개 길이 |  체중  |\n|:---------:|:---------:|:---------:|:---------:|:------:|\n|  Adelie   | 38.79 mm  | 18.35 mm  | 189.95 mm | 3700 g |\n| Chinstrap | 48.83 mm  | 18.42 mm  | 195.82 mm | 3733 g |\n|  Gentoo   | 47.50 mm  | 14.98 mm  | 217.19 mm | 5076 g |\n\n### 🎢분석 \n\n-   **부리 길이:** Chinstrap 펭귄이 가장 길고(48.83 mm), Adelie가 가장 짧음(38.79 mm).\n\n-   **부리 깊이:** 세 종 모두 비슷하지만, Gentoo 펭귄이 가장 얕음(14.98 mm).\n\n-   **날개 길이:** Gentoo 펭귄이 가장 길고(217.19 mm), Adelie가 가장 짧음(189.95 mm).\n\n-   **몸무게:** Gentoo 펭귄이 가장 무거움(5076 g), Adelie가 가장 가벼움(3700 g).\n\n## 3. 종별 서식지(island) 분포\n\n``` python\n# 종별 서식지 분포\nspecies_island = penguins.groupby([\"species\", \"island\"]).size()\nprint(species_island)\n```\n\n|    종     |  서식지   | 개체 수 |\n|:---------:|:---------:|:-------:|\n|  Adelie   |  Biscoe   |   44    |\n|  Adelie   |   Dream   |   56    |\n|  Adelie   | Torgersen |   52    |\n| Chinstrap |   Dream   |   68    |\n|  Gentoo   |  Biscoe   |   124   |\n\n### 🎢분석\n\n-   Adelie 펭귄은 **세 개의 섬(Biscoe, Dream, Torgersen)** 모두에서 발견됨.\n\n-   Chinstrap 펭귄은 **Dream 섬**에서만 발견됨.\n\n-   Gentoo 펭귄은 **Biscoe 섬**에서만 발견됨.\n\n## 4. 종별 성별 (sex) 분포\n\n``` python\n# 종별 성별 분포\nspecies_sex = penguins.groupby([\"species\", \"sex\"]).size()\nprint(species_sex)\n```\n\n| 종(species) | 성별(sex) | 개체 수 |\n|:-----------:|:---------:|:-------:|\n|   Adelie    |   Male    |   73    |\n|   Adelie    |  Female   |   73    |\n|  Chinstrap  |   Male    |   34    |\n|  Chinstrap  |  Female   |   34    |\n|   Gentoo    |   Male    |   58    |\n|   Gentoo    |  Female   |   61    |\n\n### 🎢분석\n\n-   모든 종에서 **암수 개체 수가 거의 비슷함**.\n\n-   성비는 Adelie와 Chinstrap에서 정확히 1:1이며, Gentoo는 수컷이 약간 많음.\n\n## **5. 결론: 종별 특징 요약**\n\n| 종(Species) | 주요 특징 |\n|:---------------------:|:-----------------------------------------------:|\n| **Adelie** | 부리 길이가 가장 짧고, 몸무게가 가장 가벼움 (3700g). 세 개의 섬에서 발견됨. |\n| **Chinstrap** | 부리 길이가 가장 길고(48.83 mm), Dream 섬에서만 발견됨. |\n| **Gentoo** | 몸무게가 가장 무겁고(5076 g), 날개 길이가 가장 김(217.19 mm). Biscoe 섬에서만 발견됨. |\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [],
    "includes": {}
  }
}